export const courseTagDesc = {
    TMM: "Institutt for maskinteknikk og produksjon",
    TPK: "Institutt for maskinteknikk og produksjon",
    TBA: "Institutt for bygg- og miljøteknikk (NB: ikke komplett)",
    TEP: "Institutt for energi- og prosessteknikk",
    TIØ: "Institutt for industriell økonomi og teknologiledelse (NB: ikke komplett)",
    TKT: "Institutt for konstruksjonsteknikk",
    TMA: "Institutt for matematiske fag",
    TMR: "Institutt for marin teknikk",
    TPG: "Institutt for geovitenskap og petroleum (NB: ikke komplett)",
    TTK: "Institutt for teknisk kybernetikk",
    TDT: "Institutt for datateknologi og informatikk",
}

export const courseTagObj = {
    TMM: false,
    TPK: false,
    TBA: false,
    TEP: false,
    TIØ: false,
    TKT: false,
    TMA: false,
    TMR: false,
    TPG: false,
    TTK: false,
    TDT: false,
}

const tma_courses = {
    tma4130: {
        name: "TMA4130",
        subname: "Matematikk 4N",
        term: 0,
        topics: [4, 5],
        prerequisites: [],
    },
    tma4145: {
        name: "TMA4145",
        subname: "Lineære Metoder",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4160: {
        name: "TMA4160",
        subname: "Kryptografi",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4195: {
        name: "TMA4195",
        subname: "Matematisk modellering",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4205: {
        name: "TMA4205",
        subname: "Numerisk lineær algebra",
        term: 0,
        topics: [5],
        prerequisites: [],
    },
    tma4215: {
        name: "TMA4215",
        subname: "Numerisk matematikk",
        term: 0,
        topics: [4, 5],
        prerequisites: [],
    },
    tma4220: {
        name: "TMA4220",
        subname: "Numerisk løsning av partielle differensialligninger med elementmetoden",
        term: 0,
        topics: [4, 5],
        prerequisites: [],
    },
    tma4225: {
        name: "TMA4225",
        subname: "Analysens grunnlag",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4265: {
        name: "TMA4254",
        subname: "Stokastisk modellering",
        term: 0,
        topics: [3],
        prerequisites: [],
    },
    tma4285: {
        name: "TMA4285",
        subname: "Tidsrekker",
        term: 0,
        topics: [3, 4],
        prerequisites: [],
    },
    tma4295: {
        name: "TMA4295",
        subname: "Statistisk infrens",
        term: 0,
        topics: [3],
        prerequisites: [],
    },
    tma4305: {
        name: "TMA4305",
        subname: "Partielle differensialligninger",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4315: {
        name: "TMA4315",
        subname: "Generaliserte lineære modeller",
        term: 0,
        topics: [4],
        prerequisites: [],
    },
    tma4150: {
        name: "TMA4150",
        subname: "Algebra",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4165: {
        name: "TMA4165",
        subname: "Differensialligninger og dynamiske systemer",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4170: {
        name: "TMA4170",
        subname: "Fourieranalyse",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4175: {
        name: "TMA4175",
        subname: "Kompleks analyse",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4180: {
        name: "TMA4180",
        subname: "Optimering 1",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4183: {
        name: "TMA4183",
        subname: "Optimering 2",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4190: {
        name: "TMA4190",
        subname: "Introduksjon til topologi",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4192: {
        name: "TMA4192",
        subname: "Differensialtopologi",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4212: {
        name: "TMA4212",
        subname: "Numerisk løsning av differensialligninger med differansemetoder",
        term: 1,
        topics: [4, 5],
        prerequisites: [],
    },
    tma4230: {
        name: "TMA4230",
        subname: "Funksjonsanalyse",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
    tma4250: {
        name: "TMA4250",
        subname: "Romlig statistikk",
        term: 1,
        topics: [3],
        prerequisites: [],
    },
    tma4255: {
        name: "TMA4255",
        subname: "Anvendt statistikk",
        term: 1,
        topics: [3],
        prerequisites: [],
    },
    tma4267: {
        name: "TMA4267",
        subname: "Lineære statistiske modeller",
        term: 1,
        topics: [3],
        prerequisites: [],
    },
    tma4268: {
        name: "TMA4268",
        subname: "Statistisk læring",
        term: 1,
        topics: [3],
        prerequisites: [],
    },
    tma4275: {
        name: "TMA4275",
        subname: "Levetidsanalyse",
        term: 1,
        topics: [3, 4],
        prerequisites: [],
    },
    tma4300: {
        name: "TMA4300",
        subname: "Beregningskrevende statistiske metoder",
        term: 1,
        topics: [3],
        prerequisites: [],
    },
    tma4320: {
        name: "TMA4320",
        subname: "Introduksjon til vitenskapelige beregninger",
        term: 1,
        topics: [4],
        prerequisites: [],
    },
}

const tep_courses = {
    tep4120h: {
        name: "TEP4120",
        subname: "Termodynamikk 1",
        term: 0,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4135: {
        name: "TEP4135",
        subname: "Fluidmekanikk 2",
        term: 0,
        topics: [15],
        prerequisites: [],
    },
    tep4156: {
        name: "TEP4156",
        subname: "Viskøse strømninger og grensesjikt",
        term: 0,
        topics: [14, 15],
        prerequisites: [],
    },
    tep4165: {
        name: "TEP4165",
        subname: "Numerisk varme- og strømningsteknikk",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4175: {
        name: "TEP4175",
        subname: "Design av en vindturbin",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4185: {
        name: "TEP4185",
        subname: "Naturgassteknologi",
        term: 0,
        topics: [16, 17],
        prerequisites: [],
    },
    tep4212: {
        name: "TEP4212",
        subname: "Gassrensing og utslippskontroll",
        term: 0,
        topics: [16, 17],
        prerequisites: [],
    },
    tep4223: {
        name: "TEP4223",
        subname: "Livssyklusanalyse",
        term: 0,
        topics: [16, 17],
        prerequisites: [],
    },
    tep4225: {
        name: "TEP4225",
        subname: "Energi og miljø",
        term: 0,
        topics: [16, 17],
        prerequisites: [],
    },
    tep4235: {
        name: "TEP4235",
        subname: "Energibruk i bygninger",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4240: {
        name: "TEP4240",
        subname: "Systemsimulering",
        term: 0,
        topics: [0, 16],
        prerequisites: [],
    },
    tep4270: {
        name: "TEP4270",
        subname: "Bioenergi: Teknikk og system",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4285: {
        name: "TEP4285",
        subname: "Materialstrømanalyse",
        term: 0,
        topics: [15],
        prerequisites: [],
    },
    tep4300: {
        name: "TEP4300",
        subname: "Klimavern",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4310: {
        name: "TEP4310",
        subname: "Avfallsteknologi og ressursgjenvinning",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4315: {
        name: "TEP4315",
        subname: "Inneklima",
        term: 0,
        topics: [16],
        prerequisites: [],
    },
    tep4112: {
        name: "TEP4112",
        subname: "Turbulente strømninger",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4120v: {
        name: "TEP4120",
        subname: "Termodynamikk 1",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4125: {
        name: "TEP4125",
        subname: "Termodynamikk 2",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4130: {
        name: "TEP4130",
        subname: "Varme- og massetransport",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4160: {
        name: "TEP4160",
        subname: "Aerodynamikk",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4170: {
        name: "TEP4170",
        subname: "Varme- og forbrenningsteknikk",
        term: 1,
        topics: [15, 16, 17],
        prerequisites: [],
    },
    tep4195: {
        name: "TEP4195",
        subname: "Turbomaskiner",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4200: {
        name: "TEP4200",
        subname: "Konstruksjon, drift og vedlikehold av hydrauliske strømningsmaskiner",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4220: {
        name: "TEP4220",
        subname: "Forståelse og kvantifisering av miljøpåvirkninger på økosystem",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4222: {
        name: "TEP4222",
        subname: "Kryssiøpsanalyse, handel og miljø",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4245: {
        name: "TEP4245",
        subname: "Klimateknikk",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4250: {
        name: "TEP4250",
        subname: "Fierfase teknikk",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4255: {
        name: "TEP4255",
        subname: "Varmepumpende prosesser og systemer",
        term: 1,
        topics: [15, 16, 17],
        prerequisites: [],
    },
    tep4260: {
        name: "TEP4260",
        subname: "Varmepumper for bygningsklimatisering",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4265: {
        name: "TEP4265",
        subname: "Prosessering og termisk behandling av næringsmidler",
        term: 1,
        topics: [15, 16],
        prerequisites: [],
    },
    tep4280: {
        name: "TEP4280",
        subname: "Introduksjon til numerisk strømningsberegning",
        term: 1,
        topics: [5, 14, 15],
        prerequisites: [],
    },
    tep4290: {
        name: "TEP4290",
        subname: "Modellering av det bygde miljø",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tep4295: {
        name: "TEP4295",
        subname: "Miljøanalyse og industriell økologi",
        term: 1,
        topics: [],
        prerequisites: [],
    },
}

const tpk_courses = {
    tpk4100: {
        name: "TPK4100",
        subname: "Produksjonsledelse",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tpk4120: {
        name: "TPK4120",
        subname: "Industriell sikkerhet og pålitelighet",
        term: 0,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4125: {
        name: "TPK4125",
        subname: "Mekatronikk",
        term: 0,
        topics: [10],
        prerequisites: [],
    },
    tpk4126: {
        name: "TPK4126",
        subname: "Undervannskontrollsystemer",
        term: 0,
        topics: [10, 12],
        prerequisites: [],
    },
    tpk4140: {
        name: "TPK4140",
        subname: "Driftsikkerhet og vedlikeholdsstyring",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tpk4141: {
        name: "TPK4141",
        subname: "Innovasjon, design og produksjon 1",
        term: 0,
        topics: [6, 7, 8],
        prerequisites: [],
    },
    tpk4160: {
        name: "TPK4160",
        subname: "Verdikjedestyring",
        term: 0,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4161: {
        name: "TPK4161",
        subname: "Verdikjedeanalyse",
        term: 0,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4165: {
        name: "TPK4165",
        subname: "ERP og PLM systemer",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tpk4170: {
        name: "TPK4170",
        subname: "Robotteknikk",
        term: 0,
        topics: [10, 11],
        prerequisites: [],
    },
    tpk4195: {
        name: "TPK4195",
        subname: "Verkstedteknisk måleteknikk",
        term: 0,
        topics: [6, 7],
        prerequisites: [],
    },
    tpk4420: {
        name: "TPK4420",
        subname: "Fleksibilitet i prosjekter",
        term: 0,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4430: {
        name: "TPK4430",
        subname: "Produksjonsledelse og logistikk",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tpk4440: {
        name: "TPK4440",
        subname: "Maskinering og additiv tilvirkning",
        term: 0,
        topics: [6, 7],
        prerequisites: [],
    },
    tpk4450: {
        name: "TPK4450",
        subname: "Datadrevet Prognose",
        term: 0,
        topics: [7, 9],
        prerequisites: [],
    },
    tpk5100: {
        name: "TPK5100",
        subname: "Praktisk prosjektledelse",
        term: 0,
        topics: [23, 7],
        prerequisites: [],
    },
    tpk5115: {
        name: "TPK5115",
        subname: "Risikostyring i prosjekter",
        term: 0,
        topics: [23, 7],
        prerequisites: [],
    },
    tpk4165: {
        name: "TPK4165",
        subname: "Pålitelighetsstyring og dataanalyse",
        term: 0,
        topics: [7, 9],
        prerequisites: [],
    },
    tpk5170: {
        name: "TPK5170",
        subname: "Design og pålitelighetsvurdering av digitaliserte sikkerhetssystemer",
        term: 0,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4110: {
        name: "TPK4110",
        subname: "Kvalitets- og prestasjonsfokusert ledelse",
        term: 1,
        topics: [23, 7],
        prerequisites: [],
    },
    tpk4115: {
        name: "TPK4115",
        subname: "Praktisk prosjektledelse",
        term: 1,
        topics: [23, 7],
        prerequisites: [],
    },
    tpk4128: {
        name: "TPK4128",
        subname: "Industriell mekatronikk",
        term: 1,
        topics: [10],
        prerequisites: [],
    },
    tpk4131: {
        name: "TPK4131",
        subname: "Design av industrielle logistikksystem",
        term: 1,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4135: {
        name: "TPK4135",
        subname: "Produksjonslogistikk",
        term: 1,
        topics: [7],
        prerequisites: [],
    },
    tpk4142: {
        name: "TPK4142",
        subname: "Innovasjon, design og produksjon 2",
        term: 1,
        topics: [6, 7, 8],
        prerequisites: [],
    },
    tpk4162: {
        name: "TPK4162",
        subname: "Bærekraftig og teknologisk produksjon og logistikk",
        term: 1,
        topics: [6, 7],
        prerequisites: [],
    },
    tpk4164: {
        name: "TPK4164",
        subname: "Skipsbygging og kundespesifikk produksjon",
        term: 1,
        topics: [7, 13],
        prerequisites: [],
    },
    tpk4171: {
        name: "TPK4171",
        subname: "Avansert industriell robotteknikk",
        term: 1,
        topics: [10, 11],
        prerequisites: [],
    },
    tpk4180: {
        name: "TPK4180",
        subname: "Produksjonsstrategi",
        term: 1,
        topics: [7],
        prerequisites: [],
    },
    tpk4185: {
        name: "TPK4185",
        subname: "Industriell systemdesign",
        term: 1,
        topics: [6, 7, 10],
        prerequisites: [],
    },
    tpk4186: {
        name: "TPK4186",
        subname: "Avanserte verktøy for Performance Engineering",
        term: 1,
        topics: [6, 7, 8],
        prerequisites: [],
    },
    tpk4190: {
        name: "TPK4190",
        subname: "Produksjonsteknologi",
        term: 1,
        topics: [7],
        prerequisites: [],
    },
    tpk5120: {
        name: "TPK5120",
        subname: "Grunnleggende modellutvikling",
        term: 1,
        topics: [7],
        prerequisites: [],
    },
    tpk5160: {
        name: "TPK5160",
        subname: "Risikoanalyse",
        term: 1,
        topics: [6, 7, 8, 9],
        prerequisites: [],
    },
}

const tmm_courses = {
    tmm4115: {
        name: "TMM4115",
        subname: "Produktmodellering",
        term: 0,
        topics: [6],
        prerequisites: [],
    },
    tmm4135: {
        name: "TMM4135",
        subname: "Dimensjonering basert på elementmetoden",
        term: 0,    
        topics: [5, 6],
        prerequisites: [],
    },
    tmm4150: {
        name: "TMM4150",
        subname: "Maskinkonstruksjon og mekatronikk",
        term: 0,
        topics: [6, 10],
        prerequisites: [],
    },
    tmm4151: {
        name: "TMM4151",
        subname: "Produkt- og materialtesting",
        term: 0,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4160: {
        name: "TMM4160",
        subname: "Bruddmekanikk",
        term: 0,
        topics: [6, 21, 22],
        prerequisites: [],
    },
    tmm4170: {
        name: "TMM4170",
        subname: "Korrosjon",
        term: 0,
        topics: [6, 21, 22],
        prerequisites: [],
    },
    tmm4182: {
        name: "TMM4182",
        subname: "Forming og støping av metaller",
        term: 0,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4195: {
        name: "TMM4195",
        subname: "Dimensjonering mot utmatting",
        term: 0,
        topics: [6, 21, 22],
        prerequisites: [],
    },
    tmm4220: {
        name: "TMM4220",
        subname: "Innovasjon ved Design Thinking",
        term: 0,
        topics: [6, 7, 8],
        prerequisites: [],
    },
    tmm4225: {
        name: "TMM4225",
        subname: "Ingeniørrettet samhandling i distribuerte team",
        term: 0,
        topics: [6, 7, 8],
        prerequisites: [],
    },
    tmm4250: {
        name: "TMM4250",
        subname: "Avansert produktsimulering",
        term: 0,
        topics: [6, 21],
        prerequisites: [],
    },
    tmm4270: {
        name: "TMM4270",
        subname: "Automatisering i ingeniørarbeid, introduksjon",
        term: 0,
        topics: [6, 8],
        prerequisites: [],
    },
    tmm4280: {
        name: "TMM4280",
        subname: "Avansert produktutvikling",
        term: 0,
        topics: [6, 21],
        prerequisites: [],
    },
    tmm4285: {
        name: "TMM4285",
        subname: "Livsløpsutelse for aluminiumsprodukter",
        term: 0,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4400h: {
        name: "TMM4400",
        subname: "Produktutvikling, prosjekt",
        term: 0,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4100: {
        name: "TMM4100",
        subname: "Materialteknikk",
        term: 1,
        topics: [6, 21, 22],
        prerequisites: [],
    },
    tmm4112: {
        name: "TMM4112",
        subname: "Maskindeler",
        term: 1,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4121: {
        name: "TMM4121",
        subname: "Produktutvikling",
        term: 1,
        topics: [6, 21],
        prerequisites: [],
    },
    tmm4140: {
        name: "TMM4140",
        subname: "Materialers mekaniske oppførsel",
        term: 1,
        topics: [6, 21, 22],
        prerequisites: [],
    },
    tmm4155: {
        name: "TMM4155",
        subname: "Anvendelse av elementmetoden i maskinkonstruksjon",
        term: 1,
        topics: [6, 21],
        prerequisites: [],
    },
    tmm4175: {
        name: "TMM4175",
        subname: "Plastkompositter",
        term: 1,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4205: {
        name: "TMM4205",
        subname: "Tribologi og overflateteknikk",
        term: 1,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4245: {
        name: "TMM4245",
        subname: "Fuzzy Front End",
        term: 1,
        topics: [6, 22],
        prerequisites: [],
    },
    tmm4275: {
        name: "TMM4275",
        subname: "Automatisering i ingeniørarbeid, prosjekt",
        term: 1,
        topics: [6, 8],
        prerequisites: [],
    },
    tmm4400v: {
        name: "TMM4400",
        subname: "Produktutviling, prosjekt",
        term: 1,
        topics: [6, 22],
        prerequisites: [],
    },
}

const ttk_courses = {
    ttk4100: {
        name: "TTK4100",
        subname: "Kybernetikk, introduksjon",
        term: 0,
        topics: [11],
        prerequisites: [],
    },
    ttk4115: {
        name: "TTK4115",
        subname: "Lineær systemteori",
        term: 0,
        topics: [10, 11],
        prerequisites: ["ttk4105", "tma4130"],
    },
    ttk4147: {
        name: "TTK4147",
        subname: "Sanntidssystemer",
        term: 0,
        topics: [10, 11],
        prerequisites: ["ttk4145"],
    },  
    ttk4150: {
        name: "TTK4150",
        subname: "Ulineære systemer",
        term: 0,
        topics: [10, 11],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4155: {
        name: "TTK4155",
        subname: "Industrielle og innebygde datasystemers konstruksjon",
        term: 0,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4190: {
        name: "TTK4190",
        subname: "Fartøystyring",
        term: 0,
        topics: [10, 11, 12],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4215: {
        name: "TTK4215",
        subname: "Adaptiv regulering",
        term: 0,
        topics: [11],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4220: {
        name: "TTK4220",
        subname: "Dynamikk i sosiale systemer",
        term: 0,
        topics: [11],
        prerequisites: [],
    },
    ttk4225: {
        name: "TTK4225",
        subname: "Systemteori, grunnkurs",
        term: 0,
        topics: [11],
        prerequisites: [],
    },
    ttk4230: {
        name: "TTK4230",
        subname: "Automatiseringsteknikk",
        term: 0,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4240: {
        name: "TTK4240",
        subname: "Industriell elektroteknikk",
        term: 0,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4250: {
        name: "TTK4250",
        subname: "Sensorfusjon",
        term: 0,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4555: {
        name: "TTK4555",
        subname: "Teknisk kybernetikk, fordypningsemne",
        term: 0,
        topics: [10, 11, 12],
        prerequisites: [],
    },
    ttk4101: {
        name: "TTK4101",
        subname: "Instrumentering og måleteknikk",
        term: 1,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4105: {
        name: "TTK4105",
        subname: "Reguleringsteknikk",
        term: 1,
        topics: [10, 10],
        prerequisites: ["tma4130"],
    },
    ttk4130: {
        name: "TTK4130",
        subname: "Modellering og simulering",
        term: 1,
        topics: [11],
        prerequisites: ["ttk4105"],
    },
    ttk4135: {
        name: "TTK4135",
        subname: "Optimalisering og regulering",
        term: 1,
        topics: [11],
        prerequisites: ["tma4130", "ttk4105", "ttk4115"],
    },
    ttk4145: {
        name: "TTK4145",
        subname: "Sanntidsprogrammering",
        term: 1,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4175: {
        name: "TTK4175",
        subname: "Instrumenteringssystemer",
        term: 1,
        topics: [11],
        prerequisites: [],
    },
    ttk4195: {
        name: "TTK4195",
        subname: "Modellering og regulering av roboter",
        term: 1,
        topics: [10, 11],
        prerequisites: ["ttk4105", "ttk4150"],
    },
    ttk4210: {
        name: "TTK4210",
        subname: "Avansert regulering av industrielle prosesser",
        term: 1,
        topics: [10, 11],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4235: {
        name: "TTK4235",
        subname: "Tilpassede datasystemer",
        term: 1,
        topics: [10, 11],
        prerequisites: [],
    },
    ttk4255: {
        name: "TTK4255",
        subname: "Robotsyn",
        term: 1,
        topics: [10, 11],
        prerequisites: ["tma4130", "ttk4105", "tdt4195"],
    },
    ttk4260: {
        name: "TTK4260",
        subname: "Innføring i multivariat datamodellering",
        term: 1,
        topics: [11],
        prerequisites: [],
    },
}

const tkt_courses = {
    tkt4108: {
        name: "TKT4108",
        subname: "Dynamikk, videregående kurs",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4118: {
        name: "TKT4118",
        subname: "Mekanikk 1",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4122: {
        name: "TKT4122",
        subname: "Mekanikk 2",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4124: {
        name: "TKT4124",
        subname: "Mekanikk 3",
        term: 0,
        topics: [2, 5, 6],
        prerequisites: [],
    },
    tkt4128: {
        name: "TKT4128",
        subname: "Støtmekanikk",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4146: {
        name: "TKT4146",
        subname: "Nanomekanikk",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4150: {
        name: "TKT4150",
        subname: "Biomekanikk",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4170: {
        name: "TKT4170",
        subname: "Stålkonstruksjoner 1",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4192: {
        name: "TKT4192",
        subname: "Elementmetoden i styrkeanalyse",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4196: {
        name: "TKT4196",
        subname: "Prosjektering - Sikkerhetsforhold",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4197: {
        name: "TKT4197",
        subname: "Ikkelineære elementanalyser",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4198: {
        name: "TKT4198",
        subname: "Prosjektering av konstruksjoner",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4212: {
        name: "TKT4212",
        subname: "Trekonstruksjoner 2",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4220: {
        name: "TKT4220",
        subname: "Betongkonstruksjoner 2",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4222: {
        name: "TKT4222",
        subname: "Betongkonstruksjoner 3",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4230: {
        name: "TKT4230",
        subname: "Stålkonstruksjoner 2",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4235: {
        name: "TKT4235",
        subname: "Betongteknologi",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4240: {
        name: "TKT4240",
        subname: "BM1 Bygningsmaterialer",
        term: 0,
        topics: [],
        prerequisites: [],
    },
    tkt4102: {
        name: "TKT4102",
        subname: "Dynamikk",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4116: {
        name: "TKT4116",
        subname: "Mekanikk 1",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4123: {
        name: "TKT4123",
        subname: "Mekanikk 2",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4126: {
        name: "TKT4126",
        subname: "Mekanikk",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4135: {
        name: "TKT4135",
        subname: "Materialmekanikk",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4140: {
        name: "TKT4140",
        subname: "Numeriske beregninger",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4145: {
        name: "TKT4145",
        subname: "Elementmetoden i ingeniørvitenskap",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4175: {
        name: "TKT4175",
        subname: "Betongkonstruksjoner 1",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4180: {
        name: "TKT4180",
        subname: "Konstruksjonsmekanikk, beregningsmetoder",
        term: 1,
        topics: [2, 5, 6],
        prerequisites: [],
    },
    tkt4201: {
        name: "TKT4201",
        subname: "Konstruksjonsdynamikk",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4211: {
        name: "TKT4211",
        subname: "Trekonstruksjoner 1",
        term: 1,
        topics: [],
        prerequisites: [],
    },
    tkt4215: {
        name: "TKT4215",
        subname: "Betongteknologi",
        term: 1,
        topics: [],
        prerequisites: [],
    },
}

const tba_courses = {
    tba4236: {
        name: "TBA4236",
        subname: "Teoretisk geomatikk",
        term: 0,
        topics: [19],
        prerequisites: [],
    },
    tba4250: {
        name: "TBA4250",
        subname: "Geografisk informasjonsbehandling 2",
        term: 1,
        topics: [19],
        prerequisites: [],
    },
    tba4240: {
        name: "TBA4240",
        subname: "Geografisk informasjonsbehandling 1",
        term: 0,
        topics: [19],
        prerequisites: [],
    },
    tba4231: {
        name: "TBA4231",
        subname: "Anvendt geomatikk",
        term: 0,
        topics: [19],
        prerequisites: [],
    },
}

const tpg_courses = {
    tpg4105: {
        name: "TPG4105",
        subname: "Petroleumsteknologi, grunnkurs",
        term: 0,
        topics: [17, 18],
        prerequisites: [],
    },
}

const tmr_courses = {
    tmr4105: {
        name: "TMR4105",
        subname: "Marin teknikk - Grunnlag",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4115: {
        name: "TMR4115",
        subname: "Prosjekteringsmetoder",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4130: {
        name: "TMR4130",
        subname: "Risikoanalyse og sikkerhetsledelse i maritim transport",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4137: {
        name: "TMR4137",
        subname: "Bærekraftig utnyttelse av marine ressurser",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4167: {
        name: "TMR4167",
        subname: "Marin teknikk, konstruksjoner",
        term: 0,
        topics: [13],
        prerequisites: [],
    },
    tmr4182: {
        name: "TMR4182",
        subname: "Marin dynamikk",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4190: {
        name: "TMR4190",
        subname: "Elementmetoden anvendt i konstruksjonsanalyse",
        term: 0,
        topics: [6, 13, 21],
        prerequisites: [],
    },
    tmr4200: {
        name: "TMR4200",
        subname: "Utmatting og brudd i marine konstruksjoner",
        term: 0,
        topics: [6, 13, 21, 22],
        prerequisites: [],
    },
    tmr4215: {
        name: "TMR4215",
        subname: "Sjøbelastninger",
        term: 0,
        topics: [6, 13, 21],
        prerequisites: [],
    },
    tmr4230: {
        name: "TMR4230",
        subname: "Oseanografi",
        term: 0,
        topics: [14, 18],
        prerequisites: [],
    },
    tmr4235: {
        name: "TMR4235",
        subname: "Sjøbelastningsstatistikk",
        term: 0,
        topics: [3, 13, 14],
        prerequisites: [],
    },
    tmr4240: {
        name: "TMR4240",
        subname: "Marine reguleringssytemer 1",
        term: 0,
        topics: [12],
        prerequisites: [],
    },
    tmr4260: {
        name: "TMR4260",
        subname: "Driftsteknikk - sikkerhet og vedlikehold",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4275: {
        name: "TMR4275",
        subname: "Modellering, simulering og analyse av dynamiske system",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4300: {
        name: "TMR4300",
        subname: "Eksperimentell og numerisk hydrodynamikk",
        term: 0,
        topics: [3, 14],
        prerequisites: [],
    },
    tmr4305: {
        name: "TMR4305",
        subname: "Statisk og dynamisk analyse av marine konstruksjoner",
        term: 0,
        topics: [13],
        prerequisites: [],
    },
    tmr4325: {
        name: "TMR4325",
        subname: "Ingeniørvitenskap og IKT, introduksjon",
        term: 0,
        topics: [6, 8, 13, 19, 21],
        prerequisites: [],
    },
    tmr4335: {
        name: "TMR4335",
        subname: "Marin teknikk - Propulsjonssystemer, sikkerhet og miljø",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4400: {
        name: "TMR4400",
        subname: "Marin teknikk, bransjeorientering",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4120: {
        name: "TMR4120",
        subname: "Undervannsteknikk, grunnlag",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4135: {
        name: "TMR4135",
        subname: "Prosjekteringsmetoder 2: Spesialfartøy",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4140: {
        name: "TMR4140",
        subname: "Fartøyprosjektering",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4170: {
        name: "TMR4170",
        subname: "Marine konstruksjoner",
        term: 0,
        topics: [13, 21],
        prerequisites: [],
    },
    tmr4195: {
        name: "TMR4195",
        subname: "Havkonstruksjoner",
        term: 0,
        topics: [13, 21],
        prerequisites: [],
    },
    tmr4205: {
        name: "TMR4205",
        subname: "Knekking og sammenbrudd av marine konstruksjoner",
        term: 0,
        topics: [6, 13, 21, 22],
        prerequisites: [],
    },
    tmr4217: {
        name: "TMR4217",
        subname: "Hydrodynamikk for hurtiggående fartøy",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4220: {
        name: "TMR4220",
        subname: "Skipshydrodynamikk",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4222: {
        name: "TMR4222",
        subname: "Maskineri - Design og drift 1",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4225: {
        name: "TMR4225",
        subname: "Marine operasjoner",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4243: {
        name: "TMR4243",
        subname: "Marine reguleringssystemer 2",
        term: 0,
        topics: [12],
        prerequisites: [],
    },
    tmr4247: {
        name: "TMR4247",
        subname: "Marin teknikk - Hydrodynamikk",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4254: {
        name: "TMR4254",
        subname: "Prosjektering av marine systemer",
        term: 0,
        topics: [13, 14],
        prerequisites: [],
    },
    tmr4280: {
        name: "TMR4280",
        subname: "Forbrenningsmotorer",
        term: 0,
        topics: [14, 16],
        prerequisites: [],
    },
    tmr4290: {
        name: "TMR4290",
        subname: "Maritime elektriske kraft- og propulsjonssystemer",
        term: 0,
        topics: [14, 15],
        prerequisites: [],
    },
    tmr4330: {
        name: "TMR4330",
        subname: "Maskineri - Design og drift 2",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4340: {
        name: "TMR4340",
        subname: "Marin CFD",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
    tmr4345: {
        name: "TMR4345",
        subname: "Marin datalab",
        term: 0,
        topics: [14],
        prerequisites: [],
    },
}

const tiø_courses = {
    tiø4105: {
        name: "TIØ4105",
        subname: "Industriell økonomisk styring",
        term: 0,
        topics: [7, 25],
        prerequisites: [],
    },
    tiø4118: {
        name: "TIØ4118",
        subname: "Industriell økonomisk analyse",
        term: 0,
        topics: [7, 25],
        prerequisites: [],
    },
    tiø4120: {
        name: "TIØ4120",
        subname: "Operasjonsanalyse, grunnkurs",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tiø4130: {
        name: "TIØ4130",
        subname: "Optimeringsmetoder med teknisk-økonomiske anvendelser",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tiø4145: {
        name: "TIØ4145",
        subname: "Finansstyring for foretak",
        term: 0,
        topics: [7, 25],
        prerequisites: [],
    },
    tiø4146: {
        name: "TIØ4146",
        subname: "Finans for teknisk-naturvitenskapelige studenter",
        term: 0,
        topics: [25],
        prerequisites: [],
    },
    tiø4161: {
        name: "TIØ4161",
        subname: "Prosjekt- og personalledelse",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4180: {
        name: "TIØ4180",
        subname: "Innovasjonsledelse og strategi",
        term: 0,
        topics: [8, 23],
        prerequisites: [],
    },
    tiø4186: {
        name: "TIØ4186",
        subname: "Arbeidsmiljø",
        term: 0,
        topics: [24],
        prerequisites: [],
    },
    tiø4195: {
        name: "TIØ4195",
        subname: "Miljøledelse og bedriftsstrategi",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4200: {
        name: "TIØ4200",
        subname: "Sikkerhetsledelse",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4201: {
        name: "TIØ4201",
        subname: "Risikohåndtering, samfunnssikkerhet og kritisk infrastruktur",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4215: {
        name: "TIØ4215",
        subname: "Kontraktsrett og kontraktsforhandlinger",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4230: {
        name: "TIØ4230",
        subname: "Entreprenørskap og markedsorientert produktutvikling",
        term: 0,
        topics: [7, 8, 24],
        prerequisites: [],
    },
    tiø4252: {
        name: "TIØ4252",
        subname: "Teknologiledelse",
        term: 0,
        topics: [8, 24, 25],
        prerequisites: [],
    },
    tiø4265: {
        name: "TIØ4265",
        subname: "Strategisk ledelse",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4282: {
        name: "TIØ4282",
        subname: "Digitalisering - Trusler og muligheter",
        term: 0,
        topics: [23],
        prerequisites: [],
    },
    tiø4295: {
        name: "TIØ4295",
        subname: "Bedriftsøkonomi",
        term: 0,
        topics: [25],
        prerequisites: [],
    },
    tiø4300: {
        name: "TIØ4300",
        subname: "Miljøkunnskap, økosystemtjenester og bærekraft",
        term: 0,
        topics: [19, 23],
        prerequisites: [],
    },
    tiø4330: {
        name: "TIØ4330",
        subname: "Idésøk og markedsundersøkelser",
        term: 0,
        topics: [8, 24],
        prerequisites: [],
    },
    tiø4345: {
        name: "TIØ4345",
        subname: "Ledelse av bedriftsrelasjoner og -nettverk",
        term: 0,
        topics: [23, 24],
        prerequisites: [],
    },
    tiø4365: {
        name: "TIØ4365",
        subname: "Intellectual Property Management",
        term: 0,
        topics: [23, 24],
        prerequisites: [],
    },
    tiø5200: {
        name: "TIØ5200",
        subname: "Prosjektorganisasjoner",
        term: 0,
        topics: [23, 24],
        prerequisites: [],
    },
    tiø4252v: {
        name: "TIØ4252",
        subname: "Teknologiledelse",
        term: 1,
        topics: [8, 24, 25],
        prerequisites: [],
    },
}

const tdt_courses = {
    tdt4117: {
        name: "TDT4117",
        subname: "Informasjonsgjenfinning",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4136: {
        name: "TDT4136",
        subname: "Introduksjon til kunstig intelligens",
        term: 0,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4137: {
        name: "TDT4137",
        subname: "Kognitive arkitekturer",
        term: 0,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4160: {
        name: "TDT4160",
        subname: "Datamaskiner og digitalteknikk",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4165: {
        name: "TDT4165",
        subname: "Programmeringsspråk",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4173: {
        name: "TDT4173",
        subname: "Maskinlæring",
        term: 0,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4175: {
        name: "TDT4175",
        subname: "Informasjonssystemer",
        term: 0,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4195: {
        name: "TDT4195",
        subname: "Grunnleggende visuell databehandling",
        term: 0,
        topics: [0, 18, 19],
        prerequisites: [],
    },
    tdt4200: {
        name: "TDT4200",
        subname: "Parallelle beregninger",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4225: {
        name: "TDT4225",
        subname: "Store distribuerte datamengder",
        term: 0,
        topics: [0, 2],
        prerequisites: [],
    },
    tdt4250: {
        name: "TDT4250",
        subname: "Avansert programvaredesign",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4125: {
        name: "TDT4125",
        subname: "Algoritmekonstruksjon",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4150: {
        name: "TDT4150",
        subname: "Avanserte databasesystemer",
        term: 1,
        topics: [0, 2],
        prerequisites: [],
    },
    tdt4171: {
        name: "TDT4171",
        subname: "Metoder i kunstig intelligens",
        term: 1,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4180: {
        name: "TDT4180",
        subname: "Menneske maskin-interaksjon",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4186: {
        name: "TDT4186",
        subname: "Operativsystemer",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4215: {
        name: "TDT4215",
        subname: "Anbefalingssystemer",
        term: 1,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4237: {
        name: "TDT4237",
        subname: "Programvaresikkerhet",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4240: {
        name: "TDT4240",
        subname: "Programvarearkitektur",
        term: 1,
        topics: [0, 2],
        prerequisites: [],
    },
    tdt4242: {
        name: "TDT4242",
        subname: "Avansert programvareutvikling",
        term: 1,
        topics: [0, 2],
        prerequisites: [],
    },
    tdt4265: {
        name: "TDT4265",
        subname: "Datasyn og dyp læring",
        term: 1,
        topics: [0, 1],
        prerequisites: [],
    },
    tdt4300: {
        name: "TDT4300",
        subname: "Datavarehus og datagruvedrift",
        term: 1,
        topics: [0, 1, 2],
        prerequisites: [],
    },
    tdt4305: {
        name: "TDT4305",
        subname: "Big Data-arkitektur",
        term: 1,
        topics: [0, 2],
        prerequisites: [],
    },
}

const k_courses = {

}

const eit_courses = {

}

export function sortByName(courses) {
    return Object.values(courses).sort((a,b) => (a.name > b.name) ? 1 : -1);
}

export const courses = {
    tpg4105: {
        name: "TPG4105",
        subname: "Petroleumsteknologi, grunnkurs",
        term: 0,
        topics: [3],
        prerequisites: [],
    },
    tmr4215: {
        name: "TMR4215",
        subname: "Sjøbelastninger",
        term: 0,
        topics: [5, 6],
        prerequisites: [],
    },
    tmr4167: {
        name: "TMR4167",
        subname: "Marin teknikk, konstruksjoner",
        term: 0,
        topics: [5, 6],
        prerequisites: [],
    },
    tkt4180: {
        name: "TKT4180",
        subname: "Konstruksjonsmekanikk, beregningsmetoder",
        term: 1,
        topics: [2, 5, 6],
        prerequisites: [],
    },
    tkt4124: {
        name: "TKT4124",
        subname: "Mekanikk 3",
        term: 0,
        topics: [2, 5, 6],
        prerequisites: [],
    },
    tba4236: {
        name: "TBA4236",
        subname: "Teoretisk geomatikk",
        term: 0,
        topics: [0, 6],
        prerequisites: [],
    },
    tba4250: {
        name: "TBA4250",
        subname: "Geografisk informasjonsbehandling 2",
        term: 1,
        topics: [0, 6],
        prerequisites: [],
    },
    tba4240: {
        name: "TBA4240",
        subname: "Geografisk informasjonsbehandling 1",
        term: 0,
        topics: [0, 6],
        prerequisites: [],
    },
    tba4231: {
        name: "TBA4231",
        subname: "Anvendt geomatikk",
        term: 0,
        topics: [0, 6],
        prerequisites: [],
    },
    tma4130: {
        name: "TMA4130",
        subname: "Matematikk 4N",
        term: 0,
        topics: [10],
        prerequisites: [],
    },
    tiø4252: {
        name: "TIØ4252",
        subname: "Teknologiledelse",
        term: 0,
        topics: [7],
        prerequisites: [],
    },
    tiø4252v: {
        name: "TIØ4252",
        subname: "Teknologiledelse",
        term: 1,
        topics: [7],
        prerequisites: [],
    },
    tmr4160: {
        name: "TMR4160",
        subname: "Datametoder for ingeniørtekniske anvendelser",
        term: 1,
        topics: [2, 3, 5, 6],
        prerequisites: [],
    },
    tdt4136: {
        name: "TDT4136",
        subname: "Introduksjon til kunstig intelligens",
        term: 0,
        topics: [0, 4],
        prerequisites: [],
    },
    tdt4137: {
        name: "TDT4137",
        subname: "Kognitive arkitekturer",
        term: 0,
        topics: [0, 4],
        prerequisites: [],
    },
    tdt4160: {
        name: "TDT4160",
        subname: "Datamaskiner og digitalteknikk",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4165: {
        name: "TDT4165",
        subname: "Programmeringsspråk",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4173: {
        name: "TDT4173",
        subname: "Maskinlæring",
        term: 0,
        topics: [0, 4],
        prerequisites: [],
    },
    tdt4175: {
        name: "TDT4175",
        subname: "Informasjonssystemer",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4195: {
        name: "TDT4195",
        subname: "Grunnleggende visuell databehandling",
        term: 0,
        topics: [0, 3, 6],
        prerequisites: [],
    },
    tdt4200: {
        name: "TDT4200",
        subname: "Parallelle beregninger",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4225: {
        name: "TDT4225",
        subname: "Store distribuerte datamengder",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4250: {
        name: "TDT4250",
        subname: "Avansert programvaredesign",
        term: 0,
        topics: [0],
        prerequisites: [],
    },
    tdt4125: {
        name: "TDT4125",
        subname: "Algoritmekonstruksjon",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4150: {
        name: "TDT4150",
        subname: "Avanserte databasesystemer",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4171: {
        name: "TDT4171",
        subname: "Metoder i kunstig intelligens",
        term: 1,
        topics: [0, 4],
        prerequisites: [],
    },
    tdt4180: {
        name: "TDT4180",
        subname: "Menneske maskin-interaksjon",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4186: {
        name: "TDT4186",
        subname: "Operativsystemer",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4215: {
        name: "TDT4215",
        subname: "Anbefalingssystemer",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4237: {
        name: "TDT4237",
        subname: "Programvaresikkerhet",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4240: {
        name: "TDT4240",
        subname: "Programvarearkitektur",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4242: {
        name: "TDT4242",
        subname: "Avansert programvareutvikling",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4265: {
        name: "TDT4265",
        subname: "Datasyn og dyp læring",
        term: 1,
        topics: [0, 4],
        prerequisites: [],
    },
    tdt4300: {
        name: "TDT4300",
        subname: "Datavarehus og datagruvedrift",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    tdt4305: {
        name: "TDT4305",
        subname: "Big Data-arkitektur",
        term: 1,
        topics: [0],
        prerequisites: [],
    },
    ttk4115: {
        name: "TTK4115",
        subname: "Lineær systemteori",
        term: 0,
        topics: [1, 2, 5],
        prerequisites: ["ttk4105", "tma4130"],
    },
    ttk4147: {
        name: "TTK4147",
        subname: "Sanntidssystemer",
        term: 0,
        topics: [1],
        prerequisites: ["ttk4145"],
    },  
    ttk4150: {
        name: "TTK4150",
        subname: "Ulineære systemer",
        term: 0,
        topics: [1, 2, 5],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4155: {
        name: "TTK4155",
        subname: "Industrielle og innebygde datasystemers konstruksjon",
        term: 0,
        topics: [1, 2],
        prerequisites: [],
    },
    ttk4190: {
        name: "TTK4190",
        subname: "Fartøystyring",
        term: 0,
        topics: [1, 6],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4215: {
        name: "TTK4215",
        subname: "Adaptiv regulering",
        term: 0,
        topics: [1],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4105: {
        name: "TTK4105",
        subname: "Reguleringsteknikk",
        term: 1,
        topics: [1, 2, 5],
        prerequisites: ["tma4130"],
    },
    ttk4130: {
        name: "TTK4130",
        subname: "Modellering og simulering",
        term: 1,
        topics: [1, 2, 3, 5],
        prerequisites: ["ttk4105"],
    },
    ttk4135: {
        name: "TTK4135",
        subname: "Optimalisering og regulering",
        term: 1,
        topics: [1],
        prerequisites: ["tma4130", "ttk4105", "ttk4115"],
    },
    ttk4145: {
        name: "TTK4145",
        subname: "Sanntidsprogrammering",
        term: 1,
        topics: [0, 1],
        prerequisites: [],
    },
    ttk4175: {
        name: "TTK4175",
        subname: "Instrumenteringssystemer",
        term: 1,
        topics: [1],
        prerequisites: [],
    },
    ttk4195: {
        name: "TTK4195",
        subname: "Modellering og regulering av roboter",
        term: 1,
        topics: [1, 2, 5],
        prerequisites: ["ttk4105", "ttk4150"],
    },
    ttk4210: {
        name: "TTK4210",
        subname: "Avansert regulering av industrielle prosesser",
        term: 1,
        topics: [1, 2],
        prerequisites: ["ttk4105", "ttk4115"],
    },
    ttk4255: {
        name: "TTK4255",
        subname: "Robotsyn",
        term: 1,
        topics: [1],
        prerequisites: ["tma4130", "ttk4105", "tdt4195"],
    },
    tep4240: {
        name: "TEP4240",
        subname: "Systemsimulering",
        term: 0,
        topics: [2, 3, 5],
        prerequisites: [],
    },
    tpk4120: {
        name: "TPK4120",
        subname: "Industriell sikkerhet og pålitelighet",
        term: 0,
        topics: [8],
        prerequisites: [],
    },
    tpk4125: {
        name: "TPK4125",
        subname: "Mekatronikk",
        term: 0,
        topics: [1, 2, 5],
        prerequisites: [],
    },
    tpk4140: {
        name: "TPK4140",
        subname: "Driftsikkerhet og vedlikeholdsstyring",
        term: 0,
        topics: [1, 2, 8],
        prerequisites: [],
    },
    tpk4141: {
        name: "TPK4141",
        subname: "Innovasjon, design og produksjon 1",
        term: 0,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tpk4160: {
        name: "TPK4160",
        subname: "Verdikjedestyring",
        term: 0,
        topics: [2, 8],
        prerequisites: [],
    },
    tpk4161: {
        name: "TPK4161",
        subname: "Verdikjedeanalyse",
        term: 0,
        topics: [2, 8],
        prerequisites: [],
    },
    tpk4165: {
        name: "TPK4165",
        subname: "ERP og PLM systemer",
        term: 0,
        topics: [2, 8],
        prerequisites: [],
    },
    tpk4170: {
        name: "TPK4170",
        subname: "Robotteknikk",
        term: 0,
        topics: [1, 2,  5],
        prerequisites: [],
    },
    tpk4450: {
        name: "TPK4450",
        subname: "Datadrevet Prognose",
        term: 0,
        topics: [1, 2, 8],
        prerequisites: [],
    },
    tpk4110: {
        name: "TPK4110",
        subname: "Kvalitets- og prestasjonsfokusert ledelse",
        term: 1,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tpk4115: {
        name: "TPK4115",
        subname: "Praktisk prosjektledelse",
        term: 1,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4128: {
        name: "TPK4128",
        subname: "Industriell mekatronikk",
        term: 1,
        topics: [1, 2],
        prerequisites: [],
    },
    tpk4131: {
        name: "TPK4131",
        subname: "Design av industrielle logistikksystem",
        term: 1,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tpk4135: {
        name: "TPK4135",
        subname: "Produksjonslogistikk",
        term: 1,
        topics: [7, 8],
        prerequisites: [],
    },
    tpk4142: {
        name: "TPK4142",
        subname: "Innovasjon, design og produksjon 2",
        term: 1,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tpk4162: {
        name: "TPK4162",
        subname: "Bærekraftig og teknologisk produksjon og logistikk",
        term: 1,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tpk4171: {
        name: "TPK4171",
        subname: "Avansert industriell robotteknikk",
        term: 1,
        topics: [1, 2],
        prerequisites: [],
    },
    tpk4185: {
        name: "TPK4185",
        subname: "Industriell systemdesign",
        term: 1,
        topics: [1, 2],
        prerequisites: [],
    },
    tmm4115: {
        name: "TMM4115",
        subname: "Produktmodellering",
        term: 0,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tmm4151: {
        name: "TMM4151",
        subname: "Produkt- og materialtesting",
        term: 0,
        topics: [2, 7, 8],
        prerequisites: [],
    },
    tmm4160: {
        name: "TMM4160",
        subname: "Bruddmekanikk",
        term: 0,
        topics: [2, 6],
        prerequisites: [],
    },
    tmm4170: {
        name: "TMM4170",
        subname: "Korrosjon",
        term: 0,
        topics: [2, 6],
        prerequisites: [],
    },
    tmm4195: {
        name: "TMM4195",
        subname: "Dimensjonering mot utmatting",
        term: 0,
        topics: [2, 6],
        prerequisites: [],
    },
    tmm4112: {
        name: "TMM4112",
        subname: "Maskindeler",
        term: 1,
        topics: [2],
        prerequisites: [],
    },
    tmm4150: {
        name: "TMM4150",
        subname: "Maskinkonstruksjon og mekatronikk",
        term: 0,
        topics: [1, 2],
        prerequisites: [],
    },
    tmm4135: {
        name: "TMM4135",
        subname: "Dimensjonering basert på elementmetoden",
        term: 0,    
        topics: [2, 5, 6],
        prerequisites: [],
    },
    tmm4100: {
        name: "TMM4100",
        subname: "Materialteknikk",
        term: 1,
        topics: [2],
        prerequisites: [],
    },
    tmm4121: {
        name: "TMM4121",
        subname: "Produktutvikling",
        term: 1,
        topics: [2, 8],
        prerequisites: [],
    },
    tmm4140: {
        name: "TMM4140",
        subname: "Materialers mekaniske oppførsel",
        term: 1,
        topics: [2],
        prerequisites: [],
    },
    tmm4155: {
        name: "TMM4155",
        subname: "Anvendelse av elementmetoden i maskinkonstruksjon",
        term: 1,
        topics: [2, 8],
        prerequisites: [],
    },
}

export const courses_alt2 = {
    ...tma_courses,
    ...tep_courses,
    ...tpk_courses,
    ...tmm_courses,
    ...ttk_courses,
    ...tkt_courses,
    ...tba_courses,
    ...tpg_courses,
    ...tmr_courses,
    ...tiø_courses,
    ...tdt_courses,
}

export const courses_alt3 = {
    TBA: Object.values(tba_courses),
    TDT: Object.values(tdt_courses),
    TEP: Object.values(tep_courses),
    TIØ: Object.values(tiø_courses),
    TKT: Object.values(tkt_courses),
    TMA: Object.values(tma_courses),
    TMM: Object.values(tmm_courses),
    TMR: Object.values(tmr_courses),
    TPG: Object.values(tpg_courses),
    TPK: Object.values(tpk_courses),
    TTK: Object.values(ttk_courses),
}

export const sortedCourseList = Object.values(courses).sort((a,b) => (a.name > b.name) ? 1 : -1);